config/routes.rb
Rails.application.routes.draw do

  root to: 'top_pages#top'
  
  get 'user_signup',  to: 'users#new'
  get 'dev_signup',  to: 'developers#new'

  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get    'user_login' , to: 'user_sessions#new'
  post   'user_login' , to: 'user_sessions#create'
  delete 'user_logout', to: 'user_sessions#destroy'

  get    'dev_login' , to: 'dev_sessions#new'
  post   'dev_login' , to: 'dev_sessions#create'
  delete 'dev_logout', to: 'dev_sessions#destroy'

  get 'top_pages/search', to: 'top_pages#search'
  get 'top_pages/sort', to: 'top_pages#sort'

  resources :users
  resources :developers
  resources :products
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :dev_sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :show]

end

app/controllers/dev_sessions_controller.rb
class DevSessionsController < ApplicationController
  
  def new
  end
  
  def create
    @developer = Developer.find_by(email: params[:dev_session][:email].downcase)
    if @developer && @developer.authenticate(params[:dev_session][:password])
      session[:developer_id] = @developer.id
      flash[:info] = "logged in as #{@developer.developername}"
      redirect_to @developer
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:developer_id] = nil
    redirect_to root_path
  end
  
end

app/helpers/dev_sessions_helper.rb
module DevSessionsHelper
  def current_developer
    @current_developer ||= Developer.find_by(id: session[:developer_id])
  end

  def dev_logged_in?
    !!current_developer
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/dev_sessions/new.html.erb
<h1>デヴェロッパー Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:dev_session, url: dev_login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", dev_signup_path %></p>
  </div>
</div>