config/routes.rb
Rails.application.routes.draw do

  root to: 'top_pages#top'
  
  get 'user_signup',  to: 'users#new'
  get 'dev_signup',  to: 'developers#new'

  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get    'user_login' , to: 'user_sessions#new'
  post   'user_login' , to: 'user_sessions#create'
  delete 'user_logout', to: 'user_sessions#destroy'

  get    'dev_login' , to: 'dev_sessions#new'
  post   'dev_login' , to: 'dev_sessions#create'
  delete 'dev_logout', to: 'dev_sessions#destroy'

  get 'top_pages/search', to: 'top_pages#search'
  get 'top_pages/sort', to: 'top_pages#sort'

  resources :users
  resources :developers
  resources :products
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :dev_sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :show]

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :developer
  
  has_many :comments;
  
  mount_uploader :img_icon, ImageUploader
  mount_uploader :img_screenshot_01, ImageUploader
  mount_uploader :img_screenshot_02, ImageUploader
  mount_uploader :img_screenshot_03, ImageUploader
  mount_uploader :img_screenshot_04, ImageUploader
  mount_uploader :img_screenshot_05, ImageUploader
  
  #========================
  #バリデーション
  #========================
  validates :developer_id, presence: true
  validates :appname, presence: true
  
  #===========================
  #お気に入り(逆引：プロダクト〜ユーザー)
  #===========================
  has_many :reverse_bookmarks_relationship, class_name:  "Bookmark",
                                            foreign_key: "product_id",
                                            dependent:   :destroy
  has_many :bookmarking_users, through: :reverse_bookmarks_relationship, source: :user
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :logged_in_developer, only: [:create]
  before_action :set_product, only: [:edit, :update, :show]
  
  def show
    @comment = current_user.comments.build if user_logged_in?
    # has_manyを使うべし
    @comments = @product.comments
    #@comments = Comment.all.where(product_id: params[:id]) #一応こちらでもいける
    
    self.getSize
  end  
  
  def edit
    #binding.pry
    self.getSize
  end
  
  def update
    if @product.update(product_params)
      redirect_to @product.developer
      flash[:success] = "編集に成功しました"
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def new
    #binding.pry
    @product = current_developer.products.build if dev_logged_in?  
    @image_size_01 = [320,568]
    @image_size_02 = [320,568]
    @image_size_03 = [320,568]
    @image_size_04 = [320,568]
    @image_size_05 = [320,568]
  end
  
  def create
    @product = current_developer.products.build(product_params)
    if @product.save
      flash[:success] = "新規アプリを登録しました！"
      redirect_to @product.developer
    else
      render 'new'
    end
  end
  
  def getSize
    image_01=FastImage.new(@product.img_screenshot_01.url)
    if image_01.size==nil
      @image_size_01 = [320,568]
    elsif 
      @image_size_01 = image_01.size
    end
    image_02=FastImage.new(@product.img_screenshot_02.url)
    if image_02.size==nil
      @image_size_02 = [320,568]
    elsif 
      @image_size_02 = image_02.size
    end
    image_03=FastImage.new(@product.img_screenshot_03.url)
    if image_03.size==nil
      @image_size_03 = [320,568]
    elsif 
      @image_size_03 = image_03.size
    end
    image_04=FastImage.new(@product.img_screenshot_04.url)
    if image_04.size==nil
      @image_size_04 = [320,568]
    elsif 
      @image_size_04 = image_04.size
    end
    image_05=FastImage.new(@product.img_screenshot_05.url)
    if image_05.size==nil
      @image_size_05 = [320,568]
    elsif 
      @image_size_05 = image_05.size
    end
  end
  
  private
  def product_params
    params.require(:product).permit(:appname,
                                    :summary,
                                    :description,
                                    :category,
                                    :price,
                                    :model_iphone,
                                    :model_android,
                                    :model_web,
                                    :img_icon,
                                    :img_screenshot_01,
                                    :img_screenshot_02,
                                    :img_screenshot_03,
                                    :img_screenshot_04,
                                    :img_screenshot_05)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end
end

app/views/products/_product.html.erb
<div>
  <section class="user_info">
    <%= image_tag product.img_icon.url,:size => '80x80'  ,class: "gravatar" %>
    
    <%# デベロッパーページならエディットページへ%>
    <% if $app_edit_flg %>
      <%= link_to product.appname, edit_product_path(product) %><br />
      <%= product.summary %>
    <% else%>
      <%= link_to product.appname, product_path(product) %><br />
      <%= product.summary %>
    <% end %>

  </section>
  <hr />
</div>

app/views/products/edit.html.erb
<h1>
  <%= image_tag @product.img_icon.url,:size => '80x80'  %>
  <%= @product.appname %>編集
</h1>

<%= render 'shared/product_form' %>

app/views/products/new.html.erb
<h1>アプリ登録</h1>

<%= render 'shared/product_form' %>

app/views/products/show.html.erb
<div class="row">
  <aside class="col-md-3">
  </aside>
  
  <div class="col-md-6">
    <h1>
      <%=image_tag @product.img_icon.url,:size => '80x80' %>
      <%=@product.appname %>
    </h1>
    
    
      
    <font size=5>お気に入り数 (<%= @product.bookmarking_users.count %>)</font>
    

      <hr />
      
      <div style="border:solid 0px; height:568px; width:600px; overflow:auto; white-space:nowrap;">
        
        <% if @image_size_01[0] > @image_size_01[1] %>
          <%= image_tag @product.img_screenshot_01.url,:size => '568x320'  %>
        <% else %>
          <%= image_tag @product.img_screenshot_01.url,:size => '320x568'  %>
        <% end %>
        
        <% if @image_size_02[0] > @image_size_02[1] %>
          <%= image_tag @product.img_screenshot_02.url,:size => '568x320'  %>
        <% else %>
          <%= image_tag @product.img_screenshot_02.url,:size => '320x568'  %>
        <% end %>
  
        <% if @image_size_03[0] > @image_size_03[1] %>
          <%= image_tag @product.img_screenshot_03.url,:size => '568x320'  %>
        <% else %>
          <%= image_tag @product.img_screenshot_03.url,:size => '320x568'  %>
        <% end %>
  
        <% if @image_size_04[0] > @image_size_04[1] %>
          <%= image_tag @product.img_screenshot_04.url,:size => '568x320'  %>
        <% else %>
          <%= image_tag @product.img_screenshot_04.url,:size => '320x568'  %>
        <% end %>
  
        <% if @image_size_05[0] > @image_size_05[1] %>
          <%= image_tag @product.img_screenshot_05.url,:size => '568x320'  %>
        <% else %>
          <%= image_tag @product.img_screenshot_05.url,:size => '320x568'  %>
        <% end %>
      </div>

      <p /> 
      概要:<br />
      <%= @product.summary %><br />
      
      詳細:<br />
      <%= @product.description %><br />
      
      <hr />
      
      <!-- お気に入り登録 -->
      <% if user_logged_in? %>
        <% if current_user.bookmarking?(@product) %>
          <%= link_to "お気に入り解除" ,bookmark_path(@product, redirect_url: request.url), method: :delete %>
        <% else %>
          <%= link_to "お気に入り登録" ,bookmarks_path(product_id: @product.id, redirect_url: request.url), method: :post %>
        <% end %>
      <hr />
      <% end %>

      <!-- コメントフォーム -->
      <% if user_logged_in? %>
      <%# ユーザーがまだコメントしてなければフォーム表示 %>
        <% unless @comments.pluck(:user_id).include?(current_user.id) %>
          コメント:<br />
          <%= form_for(@comment) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="field">
              <%= f.text_area :comment, placeholder: "コメントを入力して下さい..." %>
              <%= f.hidden_field :product_id, :value => @product.id %>
            </div>
            <%= f.submit "Post", class: "btn btn-primary" %>
          <% end %>
        <% end %>
      <% end %>
      
      <div style="margin-top: 30px;" >
        コメント一覧:
        <ul>
          <%= render @comments %>
        </ul>
      </div>
      
    <div class="col-md-3">
    </div>  
  
  </div>
</div>