config/routes.rb
Rails.application.routes.draw do

  root to: 'top_pages#top'
  
  get 'user_signup',  to: 'users#new'
  get 'dev_signup',  to: 'developers#new'

  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get    'user_login' , to: 'user_sessions#new'
  post   'user_login' , to: 'user_sessions#create'
  delete 'user_logout', to: 'user_sessions#destroy'

  get    'dev_login' , to: 'dev_sessions#new'
  post   'dev_login' , to: 'dev_sessions#create'
  delete 'dev_logout', to: 'dev_sessions#destroy'

  get 'top_pages/search', to: 'top_pages#search'
  get 'top_pages/sort', to: 'top_pages#sort'

  resources :users
  resources :developers
  resources :products
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :dev_sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :show]

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  def new
  end
  
  def create_sns_login
    #binding.pry
    @user=User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id]=@user.id
    flash[:info] = "logged in as #{@user.nickname}"
    redirect_to @user
  end
  
  def create
    @user = User.find_by(email: params[:user_session][:email].downcase)
    if @user && @user.authenticate(params[:user_session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.nickname}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  #=======================
  #SNSログインキャンセル
  #=======================
  def failure
    flash[:danger] = "認証に失敗しました。"
    redirect_to root_url
  end
  
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/user_sessions/new.html.erb
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user_session, url: user_login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", user_signup_path %></p>
    
    <center>
      [ <%= link_to 'Twitterでログイン', '/auth/twitter' %> ]
      [ <%= link_to 'Facebookでログイン', '/auth/facebook' %> ]
      [ <%= link_to 'Googleでログイン', '/auth/google_oauth2' %> ]
    </center>
    
  </div>
</div>