config/routes.rb
Rails.application.routes.draw do

  root to: 'top_pages#top'
  
  get 'user_signup',  to: 'users#new'
  get 'dev_signup',  to: 'developers#new'

  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get    'user_login' , to: 'user_sessions#new'
  post   'user_login' , to: 'user_sessions#create'
  delete 'user_logout', to: 'user_sessions#destroy'

  get    'dev_login' , to: 'dev_sessions#new'
  post   'dev_login' , to: 'dev_sessions#create'
  delete 'dev_logout', to: 'dev_sessions#destroy'

  get 'top_pages/search', to: 'top_pages#search'
  get 'top_pages/sort', to: 'top_pages#sort'

  resources :users
  resources :developers
  resources :products
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :dev_sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :show]

end

app/views/layouts/_dropmenu.html.erb
<!--ドロップダウン化するliタグ-->

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "並び順" %> <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "新着順", top_pages_sort_path(order:0) %></li>
    <li><%= link_to "ランキング", top_pages_sort_path(order:1) %></li>
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "機種別" %> <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "すべて", top_pages_search_path(model:[1,2,3]) %></li>
    <li><%= link_to "iPhone", top_pages_search_path(model:1) %></li>
    <li><%= link_to "Android", top_pages_search_path(model:2) %></li>
    <li><%= link_to "Webゲーム", top_pages_search_path(model:3) %></li>
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "価格" %> <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "すべて", top_pages_search_path(price:[1,2]) %></li>
    <li><%= link_to "無料", top_pages_search_path(price:1) %></li>
    <li><%= link_to "有料", top_pages_search_path(price:2) %></li>
  </ul>
</li>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    
    <!--ロゴの表示-->
    <%= link_to "アプリ自慢", root_path, id:"logo" %>
    
    <!--トグルボタンの設置（スマホの場合）-->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-content">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  
  <div id="nav-content" class="collapse navbar-collapse">
    <!--リンクのリスト メニューリスト-->
    <ul class="nav navbar-nav navbar-right">
      
      <%#ユーザーログイン判定 %>
      <% if !dev_logged_in? %>
        <% if user_logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.nickname %> <b class="caret" id="headerdropmenu"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "アカウント編集", edit_user_path(current_user) %></li>
              <li><%= link_to "ログアウト", user_logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ユーザーログイン", user_login_path %></li>
        <% end %>
      <% end %>
      
      <%#デベロッパーログイン判定 %>
      <% if !user_logged_in? %>
        <% if dev_logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_developer.developername %> <b class="caret" id="headerdropmenu"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_developer %></li>
              <li><%= link_to "アカウント編集", edit_developer_path(current_developer) %></li>
              <li><%= link_to "ログアウト", dev_logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "デヴェロッパーログイン", dev_login_path %></li>
        <% end %>
      <% end %>
      
      <%#スマホでトップ・サーチページだったら %>
      <% if current_page?(root_path) or \
                            current_page?(top_pages_search_path) or \
                                                current_page?(top_pages_sort_path) %>
        <% if request.smart_phone? %>
          <%= render 'layouts/dropmenu' %>
        <% end %>
      <% end %>
      
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>アプリ自慢</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <!-- フラッシュメッセージ -->
      <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> <!-- ここまで追加 -->
      
      <%= yield %>
      
    </div>
  </body>
</html>